<Project Sdk="Aspire.AppHost.Sdk/13.5.3">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AspireUseCliBundle>true</AspireUseCliBundle>
    <UserSecretsId>b4b014f1-e8e1-4e09-a79c-ceb987bc78e8</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.MySql" Version="13.5.3" />
    <PackageReference Include="Aspire.Hosting.PostgreSQL" Version="13.5.3" />
    <PackageReference Include="Aspire.Hosting.Redis" Version="13.5.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Scarab.csproj" />
  </ItemGroup>

</Project>
